#!/bin/bash
# 0-block_all_incoming_traffic_but

# Reset UFW to defaults
sudo ufw reset

# Deny all incoming traffic
sudo ufw default deny incoming

# Allow all outgoing traffic
sudo ufw default allow outgoing

# Allow incoming SSH, HTTP, HTTPS explicitly
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable UFW
sudo ufw --force enable

# Show status
sudo ufw status verbose
