#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
    server 6926-web-01 52.91.196.92:80 check
    server 6926-web-02 54.91.184.243:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
