#!/usr/bin/env bash
# Script that transfers a file to a server using SCP

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USER="$3"
SSH_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USER@$SERVER_IP:~/"

